DisplayModeItem{
    background-color: transparent;
    margin: 0px 10px 0px 10px;
    color: #b4b4b4;
    font-size: 20px;
}

DisplayModeItem QLabel{
    font-size: 12px;
    color: #b4b4b4;
}

DisplayModeItem#Title{
    font-size: 14px;
}

DisplayModeItem[hover=true]{
    color: white;
}

DisplayModeItem[checked=true]{
    color: #01BDFF;
}

DisplayModeItem[hover=true] QLabel{
    color: white;
}

DisplayModeItem[checked=true] QLabel{
    color: #01BDFF;
}
