/**
 * Copyright (C) 2015 Deepin Technology Co., Ltd.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 **/

/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -p server /home/liliqiang/workspace/deepin/dbus-factory/xml/com.deepin.daemon.Remoting.Server.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "server.h"

/*
 * Implementation of interface class ComDeepinDaemonRemotingServerInterface
 */

ComDeepinDaemonRemotingServerInterface::ComDeepinDaemonRemotingServerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

ComDeepinDaemonRemotingServerInterface::~ComDeepinDaemonRemotingServerInterface()
{
}

