// This file is automatically generated, please don't edit manually.
import QtQuick 2.1
import Deepin.Widgets 1.0
import "../edit"

BaseEditPage {
    id: editPage
    activeExpandIndex: {
        switch (connectionSession.type) {
            case nmConnectionTypeWired: return 23;
            case nmConnectionTypeWireless: return 5;
            case nmConnectionTypeWirelessAdhoc: return 5;
            case nmConnectionTypeWirelessHotspot: return 5;
            case nmConnectionTypePppoe: return 7;
            case nmConnectionTypeMobileGsm: return 2;
            case nmConnectionTypeMobileCdma: return 2;
            case nmConnectionTypeVpnL2tp: return 9;
            case nmConnectionTypeVpnPptp: return 9;
            case nmConnectionTypeVpnVpnc: return 9;
            case nmConnectionTypeVpnOpenvpn: return 9;
            case nmConnectionTypeVpnOpenconnect: return 9;
        }
    }

    EditLineConnectionId {
        id: lineConnectionId
        connectionSession: editPage.connectionSession
        availableSections: editPage.availableSections
        availableKeys: editPage.availableKeys
        connectionData: editPage.connectionData
        errors: editPage.errors
        section: "connection"
        key: "id"
        text: dsTr("Name")
    }
    EditLineSwitchButton {
        id: lineConnectionAutoconnect
        connectionSession: editPage.connectionSession
        availableSections: editPage.availableSections
        availableKeys: editPage.availableKeys
        connectionData: editPage.connectionData
        errors: editPage.errors
        section: "connection"
        key: "autoconnect"
        text: dsTr("Automatically connect")
    }
    
    EditSectionEthernet {
        myIndex: 1
        id: sectionEthernet
        activeExpandIndex: editPage.activeExpandIndex
        connectionSession: editPage.connectionSession
        availableSections: editPage.availableSections
        availableKeys: editPage.availableKeys
        connectionData: editPage.connectionData
        errors: editPage.errors
    }
    EditSectionSeparator {relatedSection: sectionEthernet}
    
    EditSectionMobile {
        myIndex: 2
        id: sectionMobile
        activeExpandIndex: editPage.activeExpandIndex
        connectionSession: editPage.connectionSession
        availableSections: editPage.availableSections
        availableKeys: editPage.availableKeys
        connectionData: editPage.connectionData
        errors: editPage.errors
    }
    EditSectionSeparator {relatedSection: sectionMobile}
    
    EditSectionSecurity {
        myIndex: 5
        id: sectionSecurity
        activeExpandIndex: editPage.activeExpandIndex
        connectionSession: editPage.connectionSession
        availableSections: editPage.availableSections
        availableKeys: editPage.availableKeys
        connectionData: editPage.connectionData
        errors: editPage.errors
    }
    EditSectionSeparator {relatedSection: sectionSecurity}
    
    EditSectionWifi {
        myIndex: 6
        id: sectionWifi
        activeExpandIndex: editPage.activeExpandIndex
        connectionSession: editPage.connectionSession
        availableSections: editPage.availableSections
        availableKeys: editPage.availableKeys
        connectionData: editPage.connectionData
        errors: editPage.errors
    }
    EditSectionSeparator {relatedSection: sectionWifi}
    
    EditSectionPppoe {
        myIndex: 7
        id: sectionPppoe
        activeExpandIndex: editPage.activeExpandIndex
        connectionSession: editPage.connectionSession
        availableSections: editPage.availableSections
        availableKeys: editPage.availableKeys
        connectionData: editPage.connectionData
        errors: editPage.errors
    }
    EditSectionSeparator {relatedSection: sectionPppoe}
    
    EditSectionPpp {
        myIndex: 8
        id: sectionPpp
        activeExpandIndex: editPage.activeExpandIndex
        connectionSession: editPage.connectionSession
        availableSections: editPage.availableSections
        availableKeys: editPage.availableKeys
        connectionData: editPage.connectionData
        errors: editPage.errors
    }
    EditSectionSeparator {relatedSection: sectionPpp}
    
    EditSectionVpn {
        myIndex: 9
        id: sectionVpn
        activeExpandIndex: editPage.activeExpandIndex
        connectionSession: editPage.connectionSession
        availableSections: editPage.availableSections
        availableKeys: editPage.availableKeys
        connectionData: editPage.connectionData
        errors: editPage.errors
    }
    EditSectionSeparator {relatedSection: sectionVpn}
    
    EditSectionVpnL2tpIpsec {
        myIndex: 11
        id: sectionVpnL2tpIpsec
        activeExpandIndex: editPage.activeExpandIndex
        connectionSession: editPage.connectionSession
        availableSections: editPage.availableSections
        availableKeys: editPage.availableKeys
        connectionData: editPage.connectionData
        errors: editPage.errors
    }
    EditSectionSeparator {relatedSection: sectionVpnL2tpIpsec}
    
    EditSectionVpnL2tpPpp {
        myIndex: 12
        id: sectionVpnL2tpPpp
        activeExpandIndex: editPage.activeExpandIndex
        connectionSession: editPage.connectionSession
        availableSections: editPage.availableSections
        availableKeys: editPage.availableKeys
        connectionData: editPage.connectionData
        errors: editPage.errors
    }
    EditSectionSeparator {relatedSection: sectionVpnL2tpPpp}
    
    EditSectionVpnOpenvpnSecurity {
        myIndex: 15
        id: sectionVpnOpenvpnSecurity
        activeExpandIndex: editPage.activeExpandIndex
        connectionSession: editPage.connectionSession
        availableSections: editPage.availableSections
        availableKeys: editPage.availableKeys
        connectionData: editPage.connectionData
        errors: editPage.errors
    }
    EditSectionSeparator {relatedSection: sectionVpnOpenvpnSecurity}
    
    EditSectionVpnOpenvpnTlsauth {
        myIndex: 16
        id: sectionVpnOpenvpnTlsauth
        activeExpandIndex: editPage.activeExpandIndex
        connectionSession: editPage.connectionSession
        availableSections: editPage.availableSections
        availableKeys: editPage.availableKeys
        connectionData: editPage.connectionData
        errors: editPage.errors
    }
    EditSectionSeparator {relatedSection: sectionVpnOpenvpnTlsauth}
    
    EditSectionVpnOpenvpnProxies {
        myIndex: 17
        id: sectionVpnOpenvpnProxies
        activeExpandIndex: editPage.activeExpandIndex
        connectionSession: editPage.connectionSession
        availableSections: editPage.availableSections
        availableKeys: editPage.availableKeys
        connectionData: editPage.connectionData
        errors: editPage.errors
    }
    EditSectionSeparator {relatedSection: sectionVpnOpenvpnProxies}
    
    EditSectionVpnOpenvpnAdvanced {
        myIndex: 18
        id: sectionVpnOpenvpnAdvanced
        activeExpandIndex: editPage.activeExpandIndex
        connectionSession: editPage.connectionSession
        availableSections: editPage.availableSections
        availableKeys: editPage.availableKeys
        connectionData: editPage.connectionData
        errors: editPage.errors
    }
    EditSectionSeparator {relatedSection: sectionVpnOpenvpnAdvanced}
    
    EditSectionVpnPptpPpp {
        myIndex: 20
        id: sectionVpnPptpPpp
        activeExpandIndex: editPage.activeExpandIndex
        connectionSession: editPage.connectionSession
        availableSections: editPage.availableSections
        availableKeys: editPage.availableKeys
        connectionData: editPage.connectionData
        errors: editPage.errors
    }
    EditSectionSeparator {relatedSection: sectionVpnPptpPpp}
    
    EditSectionVpnVpncAdvanced {
        myIndex: 22
        id: sectionVpnVpncAdvanced
        activeExpandIndex: editPage.activeExpandIndex
        connectionSession: editPage.connectionSession
        availableSections: editPage.availableSections
        availableKeys: editPage.availableKeys
        connectionData: editPage.connectionData
        errors: editPage.errors
    }
    EditSectionSeparator {relatedSection: sectionVpnVpncAdvanced}
    
    EditSectionIpv4 {
        myIndex: 23
        id: sectionIpv4
        activeExpandIndex: editPage.activeExpandIndex
        connectionSession: editPage.connectionSession
        availableSections: editPage.availableSections
        availableKeys: editPage.availableKeys
        connectionData: editPage.connectionData
        errors: editPage.errors
    }
    EditSectionSeparator {relatedSection: sectionIpv4}
    
    EditSectionIpv6 {
        myIndex: 24
        id: sectionIpv6
        activeExpandIndex: editPage.activeExpandIndex
        connectionSession: editPage.connectionSession
        availableSections: editPage.availableSections
        availableKeys: editPage.availableKeys
        connectionData: editPage.connectionData
        errors: editPage.errors
    }
    EditSectionSeparator {relatedSection: sectionIpv6}
    
}
