// This file is automatically generated, please don't edit manully.
import QtQuick 2.1
import Deepin.Widgets 1.0
import "../edit"

BaseEditSection { 
    id: sectionVpnOpenvpnAdvanced
    virtualSection: "vs-vpn-openvpn-advanced"
    
    header.sourceComponent: EditDownArrowHeader{
        text: dsTr("VPN Advanced")
    }

    content.sourceComponent: Column { 
        EditLineSwitchButton {
            id: lineAliasVpnOpenvpnAdvancedVkEnablePort
            // connectionSession: sectionVpnOpenvpnAdvanced.connectionSession
            section: "alias-vpn-openvpn-advanced"
            key: "vk-enable-port"
            text: dsTr("Use Custom Gateway Port")
        }
        EditLineSpinner {
            id: lineAliasVpnOpenvpnAdvancedPort
            // connectionSession: sectionVpnOpenvpnAdvanced.connectionSession
            section: "alias-vpn-openvpn-advanced"
            key: "port"
            text: dsTr("Gateway Port")
            max: 65535
            min: 0
        }
        EditLineSwitchButton {
            id: lineAliasVpnOpenvpnAdvancedVkEnableRenegSeconds
            // connectionSession: sectionVpnOpenvpnAdvanced.connectionSession
            section: "alias-vpn-openvpn-advanced"
            key: "vk-enable-reneg-seconds"
            text: dsTr("Use Custom Renegotiation Interval")
        }
        EditLineSpinner {
            id: lineAliasVpnOpenvpnAdvancedRenegSeconds
            // connectionSession: sectionVpnOpenvpnAdvanced.connectionSession
            section: "alias-vpn-openvpn-advanced"
            key: "reneg-seconds"
            text: dsTr("Renegotiation Interval")
            max: 604800
            min: 0
        }
        EditLineSwitchButton {
            id: lineAliasVpnOpenvpnAdvancedCompLzo
            // connectionSession: sectionVpnOpenvpnAdvanced.connectionSession
            section: "alias-vpn-openvpn-advanced"
            key: "comp-lzo"
            text: dsTr("Use LZO data compression")
        }
        EditLineSwitchButton {
            id: lineAliasVpnOpenvpnAdvancedProtoTcp
            // connectionSession: sectionVpnOpenvpnAdvanced.connectionSession
            section: "alias-vpn-openvpn-advanced"
            key: "proto-tcp"
            text: dsTr("Use a TCP connection")
        }
        EditLineSwitchButton {
            id: lineAliasVpnOpenvpnAdvancedTapDev
            // connectionSession: sectionVpnOpenvpnAdvanced.connectionSession
            section: "alias-vpn-openvpn-advanced"
            key: "tap-dev"
            text: dsTr("Use a TAP device")
        }
        EditLineSwitchButton {
            id: lineAliasVpnOpenvpnAdvancedVkEnableTunnelMtu
            // connectionSession: sectionVpnOpenvpnAdvanced.connectionSession
            section: "alias-vpn-openvpn-advanced"
            key: "vk-enable-tunnel-mtu"
            text: dsTr("Use Custom Tunnel MTU")
        }
        EditLineSpinner {
            id: lineAliasVpnOpenvpnAdvancedTunnelMtu
            // connectionSession: sectionVpnOpenvpnAdvanced.connectionSession
            section: "alias-vpn-openvpn-advanced"
            key: "tunnel-mtu"
            text: dsTr("MTU")
            max: 65535
            min: 0
        }
        EditLineSwitchButton {
            id: lineAliasVpnOpenvpnAdvancedVkEnableFragmentSize
            // connectionSession: sectionVpnOpenvpnAdvanced.connectionSession
            section: "alias-vpn-openvpn-advanced"
            key: "vk-enable-fragment-size"
            text: dsTr("Use Custom UDP Fragment Size")
        }
        EditLineSpinner {
            id: lineAliasVpnOpenvpnAdvancedFragmentSize
            // connectionSession: sectionVpnOpenvpnAdvanced.connectionSession
            section: "alias-vpn-openvpn-advanced"
            key: "fragment-size"
            text: dsTr("UDP Fragment Size")
            max: 65535
            min: 0
        }
        EditLineSwitchButton {
            id: lineAliasVpnOpenvpnAdvancedMssfix
            // connectionSession: sectionVpnOpenvpnAdvanced.connectionSession
            section: "alias-vpn-openvpn-advanced"
            key: "mssfix"
            text: dsTr("Restrict Tunnel TCP MSS")
        }
        EditLineSwitchButton {
            id: lineAliasVpnOpenvpnAdvancedRemoteRandom
            // connectionSession: sectionVpnOpenvpnAdvanced.connectionSession
            section: "alias-vpn-openvpn-advanced"
            key: "remote-random"
            text: dsTr("Randomize Remote Hosts")
        }
    }
}
