// This file is automatically generated, please don't edit manully.
import QtQuick 2.1
import Deepin.Widgets 1.0
import "../edit"

BaseEditSection {
    id: sectionVpnL2tpIpsec
    section: "vpn-l2tp-ipsec"
    
    header.sourceComponent: EditDownArrowHeader{
        text: dsTr("VPN IPsec")
    }

    content.sourceComponent: Column { 
        EditLineSwitchButton {
            id: lineIpsecEnabled
            key: "ipsec-enabled"
            text: dsTr("Enable IPsec")
        }
        EditLineTextInput {
            id: lineIpsecGroupName
            key: "ipsec-group-name"
            text: dsTr("Group Name")
        }
        EditLineTextInput {
            id: lineIpsecGatewayId
            key: "ipsec-gateway-id"
            text: dsTr("Group ID")
        }
        EditLinePasswordInput {
            id: lineIpsecPsk
            key: "ipsec-psk"
            text: dsTr("Password")
        }
    }
}
