// This file is automatically generated, please don't edit manully.
import QtQuick 2.1
import Deepin.Widgets 1.0
import "../edit"

BaseEditSection {
    id: sectionVpnL2tpPpp
    section: "vpn-l2tp-ppp"
    
    header.sourceComponent: EditDownArrowHeader{
        text: dsTr("VPN PPP")
    }

    content.sourceComponent: Column { 
        EditLineSwitchButton {
            id: lineVkRequireMppe
            key: "vk-require-mppe"
            text: dsTr("Use MPPE")
        }
        EditLineComboBox {
            id: lineVkMppeSecurity
            key: "vk-mppe-security"
            text: dsTr("Security")
        }
        EditLineSwitchButton {
            id: lineMppeStateful
            key: "mppe-stateful"
            text: dsTr("Stateful MPPE")
        }
        EditLineSwitchButton {
            id: lineRefuseEap
            key: "refuse-eap"
            text: dsTr("Refuse EAP Authentication")
            alwaysUpdate: true
        }
        EditLineSwitchButton {
            id: lineRefusePap
            key: "refuse-pap"
            text: dsTr("Refuse PAP Authentication")
            alwaysUpdate: true
        }
        EditLineSwitchButton {
            id: lineRefuseChap
            key: "refuse-chap"
            text: dsTr("Refuse CHAP Authentication")
            alwaysUpdate: true
        }
        EditLineSwitchButton {
            id: lineRefuseMschap
            key: "refuse-mschap"
            text: dsTr("Refuse MSCHAP Authentication")
            alwaysUpdate: true
        }
        EditLineSwitchButton {
            id: lineRefuseMschapv2
            key: "refuse-mschapv2"
            text: dsTr("Refuse MSCHAPv2 Authentication")
            alwaysUpdate: true
        }
        EditLineSwitchButton {
            id: lineNobsdcomp
            key: "nobsdcomp"
            text: dsTr("No BSD Data Compression")
        }
        EditLineSwitchButton {
            id: lineNodeflate
            key: "nodeflate"
            text: dsTr("No Deflate Data Compression")
        }
        EditLineSwitchButton {
            id: lineNoVjComp
            key: "no-vj-comp"
            text: dsTr("No TCP Header Compression")
        }
        EditLineSwitchButton {
            id: lineNopcomp
            key: "nopcomp"
            text: dsTr("No Protocol Field Compression")
        }
        EditLineSwitchButton {
            id: lineNoaccomp
            key: "noaccomp"
            text: dsTr("No Address/Control Compression")
        }
        EditLineSwitchButton {
            id: lineVkEnableLcpEcho
            key: "vk-enable-lcp-echo"
            text: dsTr("Send PPP Echo Packets")
        }
    }
}
