// This file is automatically generated, please don't edit manully.
import QtQuick 2.1
import Deepin.Widgets 1.0
import "../edit"

BaseEditSection { 
    id: sectionWifi
    virtualSection: "vs-wifi"
    
    header.sourceComponent: EditDownArrowHeader{
        text: dsTr("Wi-Fi")
    }

    content.sourceComponent: Column { 
        EditLineTextInput {
            id: line80211WirelessSsid
            // connectionSession: sectionWifi.connectionSession
            section: "802-11-wireless"
            key: "ssid"
            text: dsTr("SSID")
        }
        EditLineComboBox {
            id: line80211WirelessMode
            // connectionSession: sectionWifi.connectionSession
            section: "802-11-wireless"
            key: "mode"
            text: dsTr("Mode")
        }
        EditLineComboBox {
            id: line80211WirelessBand
            // connectionSession: sectionWifi.connectionSession
            section: "802-11-wireless"
            key: "band"
            text: dsTr("Band")
            alwaysUpdate: true
        }
        EditLineComboBox {
            id: line80211WirelessChannel
            // connectionSession: sectionWifi.connectionSession
            section: "802-11-wireless"
            key: "channel"
            text: dsTr("Channel")
            alwaysUpdate: true
        }
        EditLineEditComboBox {
            id: line80211WirelessMacAddress
            // connectionSession: sectionWifi.connectionSession
            section: "802-11-wireless"
            key: "mac-address"
            text: dsTr("Device MAC Addr")
        }
        EditLineTextInput {
            id: line80211WirelessClonedMacAddress
            // connectionSession: sectionWifi.connectionSession
            section: "802-11-wireless"
            key: "cloned-mac-address"
            text: dsTr("Cloned MAC Addr")
        }
        EditLineSwitchButton {
            id: line80211WirelessVkEnableMtu
            // connectionSession: sectionWifi.connectionSession
            section: "802-11-wireless"
            key: "vk-enable-mtu"
            text: dsTr("Custom MTU")
        }
        EditLineSpinner {
            id: line80211WirelessMtu
            // connectionSession: sectionWifi.connectionSession
            section: "802-11-wireless"
            key: "mtu"
            text: dsTr("MTU")
            max: 10000
            min: 0
        }
    }
}
