// This file is automatically generated, please don't edit manually.
import QtQuick 2.1
import Deepin.Widgets 1.0
import "../edit"

BaseEditSection { 
    id: sectionPppoe
    virtualSection: "vs-pppoe"
    
    header.sourceComponent: EditDownArrowHeader{
        text: dsTr("PPPoE")
    }

    content.sourceComponent: Column { 
        EditLineTextInput {
            id: linePppoeUsername
            connectionSession: sectionPppoe.connectionSession
            availableSections: sectionPppoe.availableSections
            availableKeys: sectionPppoe.availableKeys
            connectionData: sectionPppoe.connectionData
            errors: sectionPppoe.errors
            section: "pppoe"
            key: "username"
            text: dsTr("Username")
        }
        EditLineTextInput {
            id: linePppoeService
            connectionSession: sectionPppoe.connectionSession
            availableSections: sectionPppoe.availableSections
            availableKeys: sectionPppoe.availableKeys
            connectionData: sectionPppoe.connectionData
            errors: sectionPppoe.errors
            section: "pppoe"
            key: "service"
            text: dsTr("Service")
        }
        EditLinePasswordInput {
            id: linePppoePassword
            connectionSession: sectionPppoe.connectionSession
            availableSections: sectionPppoe.availableSections
            availableKeys: sectionPppoe.availableKeys
            connectionData: sectionPppoe.connectionData
            errors: sectionPppoe.errors
            section: "pppoe"
            key: "password"
            text: dsTr("Password")
        }
    }
}
