// This file is automatically generated, please don't edit manually.
import QtQuick 2.1
import Deepin.Widgets 1.0
import "../edit"

BaseEditSection { 
    id: sectionIpv4
    virtualSection: "vs-ipv4"
    
    header.sourceComponent: EditDownArrowHeader{
        text: dsTr("IPv4")
    }

    content.sourceComponent: Column { 
        EditLineComboBox {
            id: lineIpv4Method
            connectionSession: sectionIpv4.connectionSession
            availableSections: sectionIpv4.availableSections
            availableKeys: sectionIpv4.availableKeys
            connectionData: sectionIpv4.connectionData
            errors: sectionIpv4.errors
            section: "ipv4"
            key: "method"
            text: dsTr("Method")
        }
        EditLineIpv4Input {
            id: lineIpv4VkAddressesAddress
            connectionSession: sectionIpv4.connectionSession
            availableSections: sectionIpv4.availableSections
            availableKeys: sectionIpv4.availableKeys
            connectionData: sectionIpv4.connectionData
            errors: sectionIpv4.errors
            section: "ipv4"
            key: "vk-addresses-address"
            text: dsTr("IP Address")
            nextIpv4Input: lineIpv4VkAddressesMask
        }
        EditLineIpv4Input {
            id: lineIpv4VkAddressesMask
            connectionSession: sectionIpv4.connectionSession
            availableSections: sectionIpv4.availableSections
            availableKeys: sectionIpv4.availableKeys
            connectionData: sectionIpv4.connectionData
            errors: sectionIpv4.errors
            section: "ipv4"
            key: "vk-addresses-mask"
            text: dsTr("Netmask")
            netmaskMode: true
            nextIpv4Input: lineIpv4VkAddressesGateway
            previousIpv4Input: lineIpv4VkAddressesAddress
        }
        EditLineIpv4Input {
            id: lineIpv4VkAddressesGateway
            connectionSession: sectionIpv4.connectionSession
            availableSections: sectionIpv4.availableSections
            availableKeys: sectionIpv4.availableKeys
            connectionData: sectionIpv4.connectionData
            errors: sectionIpv4.errors
            section: "ipv4"
            key: "vk-addresses-gateway"
            text: dsTr("Gateway")
            nextIpv4Input: lineIpv4VkDns
            previousIpv4Input: lineIpv4VkAddressesMask
        }
        EditLineIpv4Input {
            id: lineIpv4VkDns
            connectionSession: sectionIpv4.connectionSession
            availableSections: sectionIpv4.availableSections
            availableKeys: sectionIpv4.availableKeys
            connectionData: sectionIpv4.connectionData
            errors: sectionIpv4.errors
            section: "ipv4"
            key: "vk-dns"
            text: dsTr("DNS Server")
            previousIpv4Input: lineIpv4VkAddressesGateway
        }
    }
}
