// This file is automatically generated, please don't edit manually.
import QtQuick 2.1
import Deepin.Widgets 1.0
import "../edit"

BaseEditSection { 
    id: sectionVpnL2tpIpsec
    virtualSection: "vs-vpn-l2tp-ipsec"
    
    header.sourceComponent: EditDownArrowHeader{
        text: dsTr("VPN IPsec")
    }

    content.sourceComponent: Column { 
        EditLineSwitchButton {
            id: lineAliasVpnL2tpIpsecIpsecEnabled
            connectionSession: sectionVpnL2tpIpsec.connectionSession
            availableSections: sectionVpnL2tpIpsec.availableSections
            availableKeys: sectionVpnL2tpIpsec.availableKeys
            connectionData: sectionVpnL2tpIpsec.connectionData
            errors: sectionVpnL2tpIpsec.errors
            section: "alias-vpn-l2tp-ipsec"
            key: "ipsec-enabled"
            text: dsTr("Enable IPsec")
        }
        EditLineTextInput {
            id: lineAliasVpnL2tpIpsecIpsecGroupName
            connectionSession: sectionVpnL2tpIpsec.connectionSession
            availableSections: sectionVpnL2tpIpsec.availableSections
            availableKeys: sectionVpnL2tpIpsec.availableKeys
            connectionData: sectionVpnL2tpIpsec.connectionData
            errors: sectionVpnL2tpIpsec.errors
            section: "alias-vpn-l2tp-ipsec"
            key: "ipsec-group-name"
            text: dsTr("Group Name")
        }
        EditLineTextInput {
            id: lineAliasVpnL2tpIpsecIpsecGatewayId
            connectionSession: sectionVpnL2tpIpsec.connectionSession
            availableSections: sectionVpnL2tpIpsec.availableSections
            availableKeys: sectionVpnL2tpIpsec.availableKeys
            connectionData: sectionVpnL2tpIpsec.connectionData
            errors: sectionVpnL2tpIpsec.errors
            section: "alias-vpn-l2tp-ipsec"
            key: "ipsec-gateway-id"
            text: dsTr("Group ID")
        }
        EditLinePasswordInput {
            id: lineAliasVpnL2tpIpsecIpsecPsk
            connectionSession: sectionVpnL2tpIpsec.connectionSession
            availableSections: sectionVpnL2tpIpsec.availableSections
            availableKeys: sectionVpnL2tpIpsec.availableKeys
            connectionData: sectionVpnL2tpIpsec.connectionData
            errors: sectionVpnL2tpIpsec.errors
            section: "alias-vpn-l2tp-ipsec"
            key: "ipsec-psk"
            text: dsTr("Password")
        }
    }
}
