// This file is automatically generated, please don't edit manually.
import QtQuick 2.1
import Deepin.Widgets 1.0
import "../edit"

BaseEditSection { 
    id: sectionVpnVpncAdvanced
    virtualSection: "vs-vpn-vpnc-advanced"
    
    header.sourceComponent: EditDownArrowHeader{
        text: dsTr("VPN Advanced")
    }

    content.sourceComponent: Column { 
        EditLineTextInput {
            id: lineAliasVpnVpncAdvancedDomain
            connectionSession: sectionVpnVpncAdvanced.connectionSession
            availableSections: sectionVpnVpncAdvanced.availableSections
            availableKeys: sectionVpnVpncAdvanced.availableKeys
            connectionData: sectionVpnVpncAdvanced.connectionData
            errors: sectionVpnVpncAdvanced.errors
            section: "alias-vpn-vpnc-advanced"
            key: "Domain"
            text: dsTr("Domain")
        }
        EditLineTextInput {
            id: lineAliasVpnVpncAdvancedVendor
            connectionSession: sectionVpnVpncAdvanced.connectionSession
            availableSections: sectionVpnVpncAdvanced.availableSections
            availableKeys: sectionVpnVpncAdvanced.availableKeys
            connectionData: sectionVpnVpncAdvanced.connectionData
            errors: sectionVpnVpncAdvanced.errors
            section: "alias-vpn-vpnc-advanced"
            key: "Vendor"
            text: dsTr("Vendor")
        }
        EditLineTextInput {
            id: lineAliasVpnVpncAdvancedApplicationVersion
            connectionSession: sectionVpnVpncAdvanced.connectionSession
            availableSections: sectionVpnVpncAdvanced.availableSections
            availableKeys: sectionVpnVpncAdvanced.availableKeys
            connectionData: sectionVpnVpncAdvanced.connectionData
            errors: sectionVpnVpncAdvanced.errors
            section: "alias-vpn-vpnc-advanced"
            key: "Application Version"
            text: dsTr("Version")
        }
        EditLineComboBox {
            id: lineAliasVpnVpncAdvancedVkEncryptionMethod
            connectionSession: sectionVpnVpncAdvanced.connectionSession
            availableSections: sectionVpnVpncAdvanced.availableSections
            availableKeys: sectionVpnVpncAdvanced.availableKeys
            connectionData: sectionVpnVpncAdvanced.connectionData
            errors: sectionVpnVpncAdvanced.errors
            section: "alias-vpn-vpnc-advanced"
            key: "vk-encryption-method"
            text: dsTr("Encryption Method")
        }
        EditLineComboBox {
            id: lineAliasVpnVpncAdvancedNatTraversalMode
            connectionSession: sectionVpnVpncAdvanced.connectionSession
            availableSections: sectionVpnVpncAdvanced.availableSections
            availableKeys: sectionVpnVpncAdvanced.availableKeys
            connectionData: sectionVpnVpncAdvanced.connectionData
            errors: sectionVpnVpncAdvanced.errors
            section: "alias-vpn-vpnc-advanced"
            key: "NAT Traversal Mode"
            text: dsTr("NAT Traversal")
        }
        EditLineComboBox {
            id: lineAliasVpnVpncAdvancedIkeDhGroup
            connectionSession: sectionVpnVpncAdvanced.connectionSession
            availableSections: sectionVpnVpncAdvanced.availableSections
            availableKeys: sectionVpnVpncAdvanced.availableKeys
            connectionData: sectionVpnVpncAdvanced.connectionData
            errors: sectionVpnVpncAdvanced.errors
            section: "alias-vpn-vpnc-advanced"
            key: "IKE DH Group"
            text: dsTr("IKE DH Group")
        }
        EditLineComboBox {
            id: lineAliasVpnVpncAdvancedPerfectForwardSecrecy
            connectionSession: sectionVpnVpncAdvanced.connectionSession
            availableSections: sectionVpnVpncAdvanced.availableSections
            availableKeys: sectionVpnVpncAdvanced.availableKeys
            connectionData: sectionVpnVpncAdvanced.connectionData
            errors: sectionVpnVpncAdvanced.errors
            section: "alias-vpn-vpnc-advanced"
            key: "Perfect Forward Secrecy"
            text: dsTr("Perfect Forward Secrecy")
        }
        EditLineSpinner {
            id: lineAliasVpnVpncAdvancedLocalPort
            connectionSession: sectionVpnVpncAdvanced.connectionSession
            availableSections: sectionVpnVpncAdvanced.availableSections
            availableKeys: sectionVpnVpncAdvanced.availableKeys
            connectionData: sectionVpnVpncAdvanced.connectionData
            errors: sectionVpnVpncAdvanced.errors
            section: "alias-vpn-vpnc-advanced"
            key: "Local Port"
            text: dsTr("Local Port")
            max: 65535
            min: 0
        }
        EditLineSwitchButton {
            id: lineAliasVpnVpncAdvancedVkDisableDpd
            connectionSession: sectionVpnVpncAdvanced.connectionSession
            availableSections: sectionVpnVpncAdvanced.availableSections
            availableKeys: sectionVpnVpncAdvanced.availableKeys
            connectionData: sectionVpnVpncAdvanced.connectionData
            errors: sectionVpnVpncAdvanced.errors
            section: "alias-vpn-vpnc-advanced"
            key: "vk-disable-dpd"
            text: dsTr("Disable Dead Peer Detection")
        }
    }
}
