// This file is automatically generated, please don't edit manully.
import QtQuick 2.1
import Deepin.Widgets 1.0
import "../edit"

BaseEditSection { 
    id: sectionVpnL2tp
    virtualSection: "vs-vpn-l2tp"
    
    header.sourceComponent: EditDownArrowHeader{
        text: dsTr("VPN")
    }

    content.sourceComponent: Column { 
        EditLineTextInput {
            id: lineAliasVpnL2tpGateway
            connectionSession: sectionVpnL2tp.connectionSession
            availableSections: sectionVpnL2tp.availableSections
            availableKeys: sectionVpnL2tp.availableKeys
            connectionData: sectionVpnL2tp.connectionData
            errors: sectionVpnL2tp.errors
            section: "alias-vpn-l2tp"
            key: "gateway"
            text: dsTr("Gateway")
        }
        EditLineTextInput {
            id: lineAliasVpnL2tpUser
            connectionSession: sectionVpnL2tp.connectionSession
            availableSections: sectionVpnL2tp.availableSections
            availableKeys: sectionVpnL2tp.availableKeys
            connectionData: sectionVpnL2tp.connectionData
            errors: sectionVpnL2tp.errors
            section: "alias-vpn-l2tp"
            key: "user"
            text: dsTr("Username")
        }
        EditLineComboBox {
            id: lineAliasVpnL2tpPasswordFlags
            connectionSession: sectionVpnL2tp.connectionSession
            availableSections: sectionVpnL2tp.availableSections
            availableKeys: sectionVpnL2tp.availableKeys
            connectionData: sectionVpnL2tp.connectionData
            errors: sectionVpnL2tp.errors
            section: "alias-vpn-l2tp"
            key: "password-flags"
            text: dsTr("Ask for Pwd")
        }
        EditLinePasswordInput {
            id: lineAliasVpnL2tpPassword
            connectionSession: sectionVpnL2tp.connectionSession
            availableSections: sectionVpnL2tp.availableSections
            availableKeys: sectionVpnL2tp.availableKeys
            connectionData: sectionVpnL2tp.connectionData
            errors: sectionVpnL2tp.errors
            section: "alias-vpn-l2tp"
            key: "password"
            text: dsTr("Password")
        }
        EditLineTextInput {
            id: lineAliasVpnL2tpDomain
            connectionSession: sectionVpnL2tp.connectionSession
            availableSections: sectionVpnL2tp.availableSections
            availableKeys: sectionVpnL2tp.availableKeys
            connectionData: sectionVpnL2tp.connectionData
            errors: sectionVpnL2tp.errors
            section: "alias-vpn-l2tp"
            key: "domain"
            text: dsTr("Domain")
        }
    }
}
