// This file is automatically generated, please don't edit manully.
import QtQuick 2.1
import Deepin.Widgets 1.0
import "../edit"

BaseEditSection {
    id: sectionSecurity
    section: "security"
    
    header.sourceComponent: EditDownArrowHeader{
        text: dsTr("Security")
    }

    content.sourceComponent: Column { 
        EditLineComboBox {
            id: lineVkKeyMgmt
            key: "vk-key-mgmt"
            text: dsTr("Security")
        }
        EditLinePasswordInput {
            id: lineWepKey0
            key: "wep-key0"
            text: dsTr("Key")
        }
        EditLinePasswordInput {
            id: linePsk
            key: "psk"
            text: dsTr("Password")
        }
        EditLineSwitchButton {
            id: lineVkEnable
            key: "vk-enable"
            text: dsTr("Use security")
        }
        EditLineComboBox {
            id: lineVkEap
            key: "vk-eap"
            text: dsTr("EAP Auth")
        }
        EditLineTextInput {
            id: lineAnonymousIdentity
            key: "anonymous-identity"
            text: dsTr("Anon Identity")
        }
        EditLineFileChooser {
            id: lineVkCaCert
            key: "vk-ca-cert"
            text: dsTr("CA Cert")
        }
        EditLineFileChooser {
            id: lineVkClientCert
            key: "vk-client-cert"
            text: dsTr("User Cert")
        }
        EditLineComboBox {
            id: linePhase1FastProvisioning
            key: "phase1-fast-provisioning"
            text: dsTr("Provisioning")
        }
        EditLineFileChooser {
            id: lineVkPacFile
            key: "vk-pac-file"
            text: dsTr("PAC file")
        }
        EditLineComboBox {
            id: linePhase1Peapver
            key: "phase1-peapver"
            text: dsTr("PEAP Version")
        }
        EditLineComboBox {
            id: linePhase2Auth
            key: "phase2-auth"
            text: dsTr("Inner Auth")
            alwaysUpdate: true
        }
        EditLineFileChooser {
            id: lineVkPrivateKey
            key: "vk-private-key"
            text: dsTr("Private Key")
        }
        EditLineTextInput {
            id: lineIdentity
            key: "identity"
            text: dsTr("Username")
        }
        EditLineComboBox {
            id: linePasswordFlags
            key: "password-flags"
            text: dsTr("Ask for Pwd")
            alwaysUpdate: true
        }
        EditLinePasswordInput {
            id: linePassword
            key: "password"
            text: dsTr("Password")
        }
        EditLineComboBox {
            id: linePrivateKeyPasswordFlags
            key: "private-key-password-flags"
            text: dsTr("Ask for Pwd")
        }
        EditLinePasswordInput {
            id: linePrivateKeyPassword
            key: "private-key-password"
            text: dsTr("Private Pwd")
        }
    }
}
