// This file is automatically generated, please don't edit manully.
import QtQuick 2.1
import Deepin.Widgets 1.0
import "../edit"

BaseEditSection {
    id: sectionVpnOpenvpnAdvanced
    section: "vpn-openvpn-advanced"
    
    header.sourceComponent: EditDownArrowHeader{
        text: dsTr("VPN Advanced")
    }

    content.sourceComponent: Column { 
        EditLineSwitchButton {
            id: lineVkEnablePort
            key: "vk-enable-port"
            text: dsTr("Use Custom Gateway Port")
        }
        EditLineSpinner {
            id: linePort
            key: "port"
            text: dsTr("Gateway Port")
            max: 65535
            min: 0
        }
        EditLineSwitchButton {
            id: lineVkEnableRenegSeconds
            key: "vk-enable-reneg-seconds"
            text: dsTr("Use Custom Renegotiation Interval")
        }
        EditLineSpinner {
            id: lineRenegSeconds
            key: "reneg-seconds"
            text: dsTr("Renegotiation Interval")
            max: 604800
            min: 0
        }
        EditLineSwitchButton {
            id: lineCompLzo
            key: "comp-lzo"
            text: dsTr("Use LZO data compression")
        }
        EditLineSwitchButton {
            id: lineProtoTcp
            key: "proto-tcp"
            text: dsTr("Use a TCP connection")
        }
        EditLineSwitchButton {
            id: lineTapDev
            key: "tap-dev"
            text: dsTr("Use a TAP device")
        }
        EditLineSwitchButton {
            id: lineVkEnableTunnelMtu
            key: "vk-enable-tunnel-mtu"
            text: dsTr("Use Custom Tunnel MTU")
        }
        EditLineSpinner {
            id: lineTunnelMtu
            key: "tunnel-mtu"
            text: dsTr("MTU")
            max: 65535
            min: 0
        }
        EditLineSwitchButton {
            id: lineVkEnableFragmentSize
            key: "vk-enable-fragment-size"
            text: dsTr("Use Custom UDP Fragment Size")
        }
        EditLineSpinner {
            id: lineFragmentSize
            key: "fragment-size"
            text: dsTr("UDP Fragment Size")
            max: 65535
            min: 0
        }
        EditLineSwitchButton {
            id: lineMssfix
            key: "mssfix"
            text: dsTr("Restrict Tunnel TCP MSS")
        }
        EditLineSwitchButton {
            id: lineRemoteRandom
            key: "remote-random"
            text: dsTr("Randomize Remote Hosts")
        }
    }
}
