// This file is automatically generated, please don't edit manully.
import QtQuick 2.1
import Deepin.Widgets 1.0
import "../edit"

BaseEditSection { 
    id: sectionEthernet
    virtualSection: "vs-ethernet"
    
    header.sourceComponent: EditDownArrowHeader{
        text: dsTr("Ethernet")
    }

    content.sourceComponent: Column { 
        EditLineEditComboBox {
            id: line8023EthernetMacAddress
            connectionSession: sectionEthernet.connectionSession
            data: sectionEthernet.data
            availableSections: sectionEthernet.availableSections
            availableKeys: sectionEthernet.availableKeys
            errors: sectionEthernet.errors
            section: "802-3-ethernet"
            key: "mac-address"
            text: dsTr("Device MAC Addr")
        }
        EditLineTextInput {
            id: line8023EthernetClonedMacAddress
            connectionSession: sectionEthernet.connectionSession
            data: sectionEthernet.data
            availableSections: sectionEthernet.availableSections
            availableKeys: sectionEthernet.availableKeys
            errors: sectionEthernet.errors
            section: "802-3-ethernet"
            key: "cloned-mac-address"
            text: dsTr("Cloned MAC Addr")
        }
        EditLineSwitchButton {
            id: line8023EthernetVkEnableMtu
            connectionSession: sectionEthernet.connectionSession
            data: sectionEthernet.data
            availableSections: sectionEthernet.availableSections
            availableKeys: sectionEthernet.availableKeys
            errors: sectionEthernet.errors
            section: "802-3-ethernet"
            key: "vk-enable-mtu"
            text: dsTr("Custom MTU")
        }
        EditLineSpinner {
            id: line8023EthernetMtu
            connectionSession: sectionEthernet.connectionSession
            data: sectionEthernet.data
            availableSections: sectionEthernet.availableSections
            availableKeys: sectionEthernet.availableKeys
            errors: sectionEthernet.errors
            section: "802-3-ethernet"
            key: "mtu"
            text: dsTr("MTU")
            max: 10000
            min: 0
        }
    }
}
