DeviceListItem QLabel{
    font-size: 12px;
    color: #b4b4b4;
}

DeviceListItem[checked="true"]{
    background-color: transparent;
    background-image: url(:/dark/images/tick_hover.png);
    background-repeat: no-repeat;
    background-position: left center;
    border-radius: 3px;
}

GenericListItem[showBgColor="false"]{
    background-image: url();
}

DeviceListItem[checked="true"] QLabel{
    color: #b4b4b4;
}

DeviceListItem QLabel:hover{
    color: white;
}
