// This file is automatically generated, please don't edit manully.
import QtQuick 2.1
import Deepin.Widgets 1.0
import "../components"

BaseEditPage {
    id: root
    activeExpandIndex: 0

    
    EditSectionGeneral {
        myIndex: 0
        id: sectionGeneral
        activeExpandIndex: root.activeExpandIndex
    }
    EditSectionSeparator {relatedSection: sectionGeneral}
    
    EditSectionEthernet {
        myIndex: 1
        id: sectionEthernet
        activeExpandIndex: root.activeExpandIndex
    }
    EditSectionSeparator {relatedSection: sectionEthernet}
    
    EditSectionMobileGsm {
        myIndex: 2
        id: sectionMobileGsm
        activeExpandIndex: root.activeExpandIndex
    }
    EditSectionSeparator {relatedSection: sectionMobileGsm}
    
    EditSectionMobileCdma {
        myIndex: 3
        id: sectionMobileCdma
        activeExpandIndex: root.activeExpandIndex
    }
    EditSectionSeparator {relatedSection: sectionMobileCdma}
    
    EditSectionWifi {
        myIndex: 4
        id: sectionWifi
        activeExpandIndex: root.activeExpandIndex
    }
    EditSectionSeparator {relatedSection: sectionWifi}
    
    EditSectionSecurity {
        myIndex: 5
        id: sectionSecurity
        activeExpandIndex: root.activeExpandIndex
    }
    EditSectionSeparator {relatedSection: sectionSecurity}
    
    EditSectionPppoe {
        myIndex: 6
        id: sectionPppoe
        activeExpandIndex: root.activeExpandIndex
    }
    EditSectionSeparator {relatedSection: sectionPppoe}
    
    EditSectionPpp {
        myIndex: 7
        id: sectionPpp
        activeExpandIndex: root.activeExpandIndex
    }
    EditSectionSeparator {relatedSection: sectionPpp}
    
    EditSectionVpnL2tp {
        myIndex: 8
        id: sectionVpnL2tp
        activeExpandIndex: root.activeExpandIndex
    }
    EditSectionSeparator {relatedSection: sectionVpnL2tp}
    
    EditSectionVpnL2tpIpsec {
        myIndex: 9
        id: sectionVpnL2tpIpsec
        activeExpandIndex: root.activeExpandIndex
    }
    EditSectionSeparator {relatedSection: sectionVpnL2tpIpsec}
    
    EditSectionVpnL2tpPpp {
        myIndex: 10
        id: sectionVpnL2tpPpp
        activeExpandIndex: root.activeExpandIndex
    }
    EditSectionSeparator {relatedSection: sectionVpnL2tpPpp}
    
    EditSectionVpnOpenconnect {
        myIndex: 11
        id: sectionVpnOpenconnect
        activeExpandIndex: root.activeExpandIndex
    }
    EditSectionSeparator {relatedSection: sectionVpnOpenconnect}
    
    EditSectionVpnOpenvpn {
        myIndex: 12
        id: sectionVpnOpenvpn
        activeExpandIndex: root.activeExpandIndex
    }
    EditSectionSeparator {relatedSection: sectionVpnOpenvpn}
    
    EditSectionVpnOpenvpnSecurity {
        myIndex: 13
        id: sectionVpnOpenvpnSecurity
        activeExpandIndex: root.activeExpandIndex
    }
    EditSectionSeparator {relatedSection: sectionVpnOpenvpnSecurity}
    
    EditSectionVpnOpenvpnTlsauth {
        myIndex: 14
        id: sectionVpnOpenvpnTlsauth
        activeExpandIndex: root.activeExpandIndex
    }
    EditSectionSeparator {relatedSection: sectionVpnOpenvpnTlsauth}
    
    EditSectionVpnOpenvpnProxies {
        myIndex: 15
        id: sectionVpnOpenvpnProxies
        activeExpandIndex: root.activeExpandIndex
    }
    EditSectionSeparator {relatedSection: sectionVpnOpenvpnProxies}
    
    EditSectionVpnOpenvpnAdvanced {
        myIndex: 16
        id: sectionVpnOpenvpnAdvanced
        activeExpandIndex: root.activeExpandIndex
    }
    EditSectionSeparator {relatedSection: sectionVpnOpenvpnAdvanced}
    
    EditSectionVpnPptp {
        myIndex: 17
        id: sectionVpnPptp
        activeExpandIndex: root.activeExpandIndex
    }
    EditSectionSeparator {relatedSection: sectionVpnPptp}
    
    EditSectionVpnPptpPpp {
        myIndex: 18
        id: sectionVpnPptpPpp
        activeExpandIndex: root.activeExpandIndex
    }
    EditSectionSeparator {relatedSection: sectionVpnPptpPpp}
    
    EditSectionVpnVpnc {
        myIndex: 19
        id: sectionVpnVpnc
        activeExpandIndex: root.activeExpandIndex
    }
    EditSectionSeparator {relatedSection: sectionVpnVpnc}
    
    EditSectionVpnVpncAdvanced {
        myIndex: 20
        id: sectionVpnVpncAdvanced
        activeExpandIndex: root.activeExpandIndex
    }
    EditSectionSeparator {relatedSection: sectionVpnVpncAdvanced}
    
    EditSectionIpv4 {
        myIndex: 21
        id: sectionIpv4
        activeExpandIndex: root.activeExpandIndex
    }
    EditSectionSeparator {relatedSection: sectionIpv4}
    
    EditSectionIpv6 {
        myIndex: 22
        id: sectionIpv6
        activeExpandIndex: root.activeExpandIndex
    }
    EditSectionSeparator {relatedSection: sectionIpv6}
    
}
