// This file is automatically generated, please don't edit manully.
import QtQuick 2.1
import Deepin.Widgets 1.0
import "../components"

BaseEditPage {
    id: root
    activeExpandIndex: 0

    EditTitle {}
    
    EditSectionSeparator {relatedSection: sectionGeneral}
    EditSectionGeneral {
        myIndex: 0
        id: sectionGeneral
        activeExpandIndex: root.activeExpandIndex
    }
    
    EditSectionSeparator {relatedSection: sectionIpv4}
    EditSectionIpv4 {
        myIndex: 1
        id: sectionIpv4
        activeExpandIndex: root.activeExpandIndex
    }
    
    EditSectionSeparator {relatedSection: sectionIpv6}
    EditSectionIpv6 {
        myIndex: 2
        id: sectionIpv6
        activeExpandIndex: root.activeExpandIndex
    }
    
    EditSectionSeparator {relatedSection: sectionPppoe}
    EditSectionPppoe {
        myIndex: 3
        id: sectionPppoe
        activeExpandIndex: root.activeExpandIndex
    }
    
    EditSectionSeparator {relatedSection: sectionPpp}
    EditSectionPpp {
        myIndex: 4
        id: sectionPpp
        activeExpandIndex: root.activeExpandIndex
    }
    
    EditSectionSeparator {relatedSection: sectionEthernet}
    EditSectionEthernet {
        myIndex: 5
        id: sectionEthernet
        activeExpandIndex: root.activeExpandIndex
    }
    
    EditSectionSeparator {relatedSection: sectionWifi}
    EditSectionWifi {
        myIndex: 6
        id: sectionWifi
        activeExpandIndex: root.activeExpandIndex
    }
    
    EditSectionSeparator {relatedSection: sectionSecurity}
    EditSectionSecurity {
        myIndex: 7
        id: sectionSecurity
        activeExpandIndex: root.activeExpandIndex
    }
    
}
