// This file is automatically generated, please don't edit manully.
import QtQuick 2.1
import Deepin.Widgets 1.0
import "../components"

BaseEditSection {
    id: sectionPpp
    section: "ppp"
    
    header.sourceComponent: EditDownArrowHeader{
        text: dsTr("PPP")
    }

    content.sourceComponent: Column { 
        EditLineSwitchButton {
            id: lineRefuseEap
            key: "refuse-eap"
            text: dsTr("!!refuse-eap")
        }
        EditLineSwitchButton {
            id: lineRefusePap
            key: "refuse-pap"
            text: dsTr("!!refuse-pap")
        }
        EditLineSwitchButton {
            id: lineRefuseChap
            key: "refuse-chap"
            text: dsTr("!!refuse-chap")
        }
        EditLineSwitchButton {
            id: lineRefuseMschap
            key: "refuse-mschap"
            text: dsTr("!!refuse-mschap")
        }
        EditLineSwitchButton {
            id: lineRefuseMschapv2
            key: "refuse-mschapv2"
            text: dsTr("!!refuse-mschapv2")
        }
        EditLineSwitchButton {
            id: lineNobsdcomp
            key: "nobsdcomp"
            text: dsTr("!!nobsdcomp")
        }
        EditLineSwitchButton {
            id: lineNodeflate
            key: "nodeflate"
            text: dsTr("!!nodeflate")
        }
        EditLineSwitchButton {
            id: lineNoVjComp
            key: "no-vj-comp"
            text: dsTr("!!no-vj-comp")
        }
        EditLineSwitchButton {
            id: lineRequireMppe
            key: "require-mppe"
            text: dsTr("!!require-mppe")
        }
        EditLineSwitchButton {
            id: lineRequireMppe128
            key: "require-mppe-128"
            text: dsTr("!!require-mppe-128")
        }
        EditLineSwitchButton {
            id: lineMppeStateful
            key: "mppe-stateful"
            text: dsTr("!!mppe-stateful")
        }
        EditLineSpinner {
            id: lineLcpEchoFailure
            key: "lcp-echo-failure"
            text: dsTr("!!lcp-echo-failure")
        }
        EditLineSpinner {
            id: lineLcpEchoInterval
            key: "lcp-echo-interval"
            text: dsTr("!!lcp-echo-interval")
        }
    }
}
