// This file is automatically generated, please don't edit manully.
import QtQuick 2.1
import Deepin.Widgets 1.0
import "../components"

BaseEditSection {
    id: sectionVpnVpnc
    section: "vpn-vpnc"
    
    header.sourceComponent: EditDownArrowHeader{
        text: dsTr("VPN")
    }

    content.sourceComponent: Column { 
        EditLineTextInput {
            key: "IPSec gateway"
            text: dsTr("Gateway")
        }
        EditLineTextInput {
            key: "Xauth username"
            text: dsTr("User Name")
        }
        EditLineComboBox {
            key: "Xauth password-flags"
            text: dsTr("Ask For Pwd")
        }
        EditLinePasswordInput {
            key: "Xauth password"
            text: dsTr("User Pwd")
        }
        EditLineTextInput {
            key: "IPSec ID"
            text: dsTr("Group Name")
        }
        EditLineComboBox {
            key: "IPSec secret-flags"
            text: dsTr("Ask For Pwd")
        }
        EditLinePasswordInput {
            key: "IPSec secret"
            text: dsTr("Group Pwd")
        }
        EditLineSwitchButton {
            key: "vk-hybrid-authmode"
            text: dsTr("Use Hybrid Authentication")
        }
        EditLineFileChooser {
            key: "CA-File"
            text: dsTr("CA File")
        }
    }
}
