// This file is automatically generated, please don't edit manully.
import QtQuick 2.1
import Deepin.Widgets 1.0
import "../components"

BaseEditSection {
    id: sectionVpnL2tpPpp
    section: "vpn-l2tp-ppp"
    
    header.sourceComponent: EditDownArrowHeader{
        text: dsTr("VPN PPP")
    }

    content.sourceComponent: Column { 
        EditLineSwitchButton {
            key: "refuse-eap"
            text: dsTr("Refuse EAP Authentication")
        }
        EditLineSwitchButton {
            key: "refuse-pap"
            text: dsTr("Refuse PAP Authentication")
        }
        EditLineSwitchButton {
            key: "refuse-chap"
            text: dsTr("Refuse CHAP Authentication")
        }
        EditLineSwitchButton {
            key: "refuse-mschap"
            text: dsTr("Refuse MSCHAP Authentication")
        }
        EditLineSwitchButton {
            key: "refuse-mschapv2"
            text: dsTr("Refuse MSCHAPv2 Authentication")
        }
        EditLineSwitchButton {
            key: "require-mppe"
            text: dsTr("Use MPPE")
            alwaysUpdate: true
        }
        EditLineSwitchButton {
            key: "require-mppe-40"
            text: dsTr("40-bit MPPE")
            alwaysUpdate: true
        }
        EditLineSwitchButton {
            key: "require-mppe-128"
            text: dsTr("128-bit MPPE")
            alwaysUpdate: true
        }
        EditLineSwitchButton {
            key: "mppe-stateful"
            text: dsTr("Stateful MPPE")
        }
        EditLineSwitchButton {
            key: "nobsdcomp"
            text: dsTr("No BSD Data Compression")
        }
        EditLineSwitchButton {
            key: "nodeflate"
            text: dsTr("No Deflate Data Compression")
        }
        EditLineSwitchButton {
            key: "no-vj-comp"
            text: dsTr("No TCP Header Compression")
        }
        EditLineSwitchButton {
            key: "nopcomp"
            text: dsTr("No Protocol Field Compression")
        }
        EditLineSwitchButton {
            key: "noaccomp"
            text: dsTr("No Address/Control Compression")
        }
        EditLineSwitchButton {
            key: "vk-enable-lcp-echo"
            text: dsTr("Send PPP Echo Packets")
        }
    }
}
