// This file is automatically generated, please don't edit manully.
import QtQuick 2.1
import Deepin.Widgets 1.0
import "../components"

BaseEditSection {
    id: sectionIpv4
    section: "ipv4"
    
    header.sourceComponent: EditDownArrowHeader{
        text: dsTr("IPv4")
    }

    content.sourceComponent: Column { 
        EditLineIpv4Input {
            id: lineVkAddressesAddress
            key: "vk-addresses-address"
            text: dsTr("IP Address")
        }
        EditLineIpv4Input {
            id: lineVkAddressesMask
            key: "vk-addresses-mask"
            text: dsTr("Netmask")
        }
        EditLineIpv4Input {
            id: lineVkAddressesGateway
            key: "vk-addresses-gateway"
            text: dsTr("Gateway")
        }
        EditLineIpv4Input {
            id: lineVkDns
            key: "vk-dns"
            text: dsTr("DNS Server")
        }
        EditLineComboBox {
            id: lineMethod
            key: "method"
            text: dsTr("Method")
        }
    }
}
