// This file is automatically generated, please don't edit manully.
import QtQuick 2.1
import Deepin.Widgets 1.0
import "../components"

BaseEditSection {
    id: sectionVpnOpenvpnAdvanced
    section: "vpn-openvpn-advanced"
    
    header.sourceComponent: EditDownArrowHeader{
        text: dsTr("VPN Advanced")
    }

    content.sourceComponent: Column { 
        EditLineSwitchButton {
            key: "vk-enable-port"
            text: dsTr("Use Custom Gateway Port")
        }
        EditLineSpinner {
            key: "port"
            text: dsTr("Gateway Port")
        }
        EditLineSwitchButton {
            key: "vk-enable-reneg-seconds"
            text: dsTr("Use Custom Renegotiation Interval")
        }
        EditLineSpinner {
            key: "reneg-seconds"
            text: dsTr("Renegotiation Interval")
        }
        EditLineSwitchButton {
            key: "comp-lzo"
            text: dsTr("Use LZO data compression")
        }
        EditLineSwitchButton {
            key: "proto-tcp"
            text: dsTr("Use a TCP connection")
        }
        EditLineSwitchButton {
            key: "tap-dev"
            text: dsTr("Use a TAP device")
        }
        EditLineSwitchButton {
            key: "vk-enable-tunnel-mtu"
            text: dsTr("Use Custom Tunnel MTU")
        }
        EditLineSpinner {
            key: "tunnel-mtu"
            text: dsTr("MTU")
        }
        EditLineSwitchButton {
            key: "vk-enable-fragment-size"
            text: dsTr("Use Custom UDP Fragment Size")
        }
        EditLineSpinner {
            key: "fragment-size"
            text: dsTr("UDP Fragment Size")
        }
        EditLineSwitchButton {
            key: "mssfix"
            text: dsTr("Restrict Tunnel TCP MSS")
        }
        EditLineSwitchButton {
            key: "remote-random"
            text: dsTr("Randomize Remote Hosts")
        }
    }
}
