// This file is automatically generated, please don't edit manully.
import QtQuick 2.1
import Deepin.Widgets 1.0
import "../components"

BaseEditSection {
    id: sectionMobileGsm
    section: "mobile-gsm"
    
    header.sourceComponent: EditDownArrowHeader{
        text: dsTr("Mobile")
    }

    content.sourceComponent: Column { 
        EditLineEditComboBox {
            id: lineNumber
            key: "number"
            text: dsTr("Number")
        }
        EditLineTextInput {
            id: lineUsername
            key: "username"
            text: dsTr("Username")
        }
        EditLineComboBox {
            id: linePasswordFlags
            key: "password-flags"
            text: dsTr("Ask for Pwd")
        }
        EditLinePasswordInput {
            id: linePassword
            key: "password"
            text: dsTr("Password")
        }
        EditLineEditComboBox {
            id: lineApn
            key: "apn"
            text: dsTr("APN")
        }
        EditLineTextInput {
            id: lineNetworkId
            key: "network-id"
            text: dsTr("Network ID")
        }
        EditLineComboBox {
            id: lineNetworkType
            key: "network-type"
            text: dsTr("Type")
        }
        EditLineSwitchButton {
            id: lineHomeOnly
            key: "home-only"
            text: dsTr("Home Network Only")
        }
        EditLinePasswordInput {
            id: linePin
            key: "pin"
            text: dsTr("PIN")
        }
    }
}
