// This file is automatically generated, please don't edit manully.
import QtQuick 2.1
import Deepin.Widgets 1.0
import "../components"

BaseEditSection {
    id: sectionSecurity
    section: "security"
    
    header.sourceComponent: EditDownArrowHeader{
        text: dsTr("Security")
    }

    content.sourceComponent: Column { 
        EditLineComboBox {
            key: "vk-key-mgmt"
            text: dsTr("Security")
        }
        EditLinePasswordInput {
            key: "wep-key0"
            text: dsTr("Key")
        }
        EditLinePasswordInput {
            key: "psk"
            text: dsTr("Password")
        }
        EditLineSwitchButton {
            key: "vk-enable"
            text: dsTr("Use security")
        }
        EditLineComboBox {
            key: "vk-eap"
            text: dsTr("EAP Auth")
        }
        EditLineTextInput {
            key: "anonymous-identity"
            text: dsTr("Anon Identity")
        }
        EditLineFileChooser {
            key: "vk-client-cert"
            text: dsTr("User Cert")
        }
        EditLineFileChooser {
            key: "vk-ca-cert"
            text: dsTr("CA Cert")
        }
        EditLineComboBox {
            key: "phase1-fast-provisioning"
            text: dsTr("Provisioning")
        }
        EditLineFileChooser {
            key: "vk-pac-file"
            text: dsTr("PAC file")
        }
        EditLineComboBox {
            key: "phase1-peapver"
            text: dsTr("PEAP Version")
        }
        EditLineComboBox {
            key: "phase2-auth"
            text: dsTr("Inner Auth")
            alwaysUpdate: true
        }
        EditLineFileChooser {
            key: "vk-private-key"
            text: dsTr("Private Key")
        }
        EditLineTextInput {
            key: "identity"
            text: dsTr("Username")
        }
        EditLinePasswordInput {
            key: "password"
            text: dsTr("Password")
        }
        EditLinePasswordInput {
            key: "private-key-password"
            text: dsTr("Private Pwd")
        }
    }
}
