// This file is automatically generated, please don't edit manully.
import QtQuick 2.1
import Deepin.Widgets 1.0
import "../components"

BaseEditSection {
    id: sectionVpnOpenconnect
    section: "vpn-openconnect"
    
    header.sourceComponent: EditDownArrowHeader{
        text: dsTr("VPN")
    }

    content.sourceComponent: Column { 
        EditLineTextInput {
            key: "gateway"
            text: dsTr("Gateway")
        }
        EditLineFileChooser {
            key: "cacert"
            text: dsTr("CA Cert")
        }
        EditLineTextInput {
            key: "proxy"
            text: dsTr("Proxy")
        }
        EditLineSwitchButton {
            key: "enable_csd_trojan"
            text: dsTr("Allow Cisco Secure Desktop Trojan")
        }
        EditLineTextInput {
            key: "csd_wrapper"
            text: dsTr("CSD Wrapper")
        }
        EditLineFileChooser {
            key: "usercert"
            text: dsTr("Uesr Cert")
        }
        EditLineFileChooser {
            key: "userkey"
            text: dsTr("Private Key")
        }
        EditLineSwitchButton {
            key: "pem_passphrase_fsid"
            text: dsTr("User FSID For Key Passphrase")
        }
    }
}
