// This file is automatically generated, please don't edit manully.
import QtQuick 2.1
import Deepin.Widgets 1.0
import "../components"

BaseEditSection {
    id: sectionVpnOpenvpnProxies
    section: "vpn-openvpn-proxies"
    
    header.sourceComponent: EditDownArrowHeader{
        text: dsTr("VPN Proxies")
    }

    content.sourceComponent: Column { 
        EditLineComboBox {
            key: "proxy-type"
            text: dsTr("Proxy Type")
        }
        EditLineTextInput {
            key: "proxy-server"
            text: dsTr("Server IP")
        }
        EditLineSpinner {
            key: "proxy-port"
            text: dsTr("Port")
        }
        EditLineSwitchButton {
            key: "proxy-retry"
            text: dsTr("Retry Indefinitely When Failed")
        }
        EditLineTextInput {
            key: "http-proxy-username"
            text: dsTr("User Name")
        }
        EditLinePasswordInput {
            key: "http-proxy-password"
            text: dsTr("Password")
        }
    }
}
