// This file is automatically generated, please don't edit manully.
import QtQuick 2.1
import Deepin.Widgets 1.0
import "../components"

BaseEditSection {
    id: sectionVpnOpenconnect
    section: "vpn-openconnect"
    
    header.sourceComponent: EditDownArrowHeader{
        text: dsTr("VPN")
    }

    content.sourceComponent: Column { 
        EditLineTextInput {
            key: "gateway"
            text: dsTr("!!gateway")
        }
        EditLineFileChooser {
            key: "cacert"
            text: dsTr("!!cacert")
        }
        EditLineTextInput {
            key: "proxy"
            text: dsTr("!!proxy")
        }
        EditLineSwitchButton {
            key: "enable_csd_trojan"
            text: dsTr("!!enable_csd_trojan")
        }
        EditLineTextInput {
            key: "csd_wrapper"
            text: dsTr("!!csd_wrapper")
        }
        EditLineFileChooser {
            key: "usercert"
            text: dsTr("!!usercert")
        }
        EditLineFileChooser {
            key: "userkey"
            text: dsTr("!!userkey")
        }
        EditLineSwitchButton {
            key: "pem_passphrase_fsid"
            text: dsTr("!!pem_passphrase_fsid")
        }
    }
}
