// This file is automatically generated, please don't edit manully.
import QtQuick 2.1
import Deepin.Widgets 1.0
import "../components"

BaseEditSection {
    id: sectionWifi
    section: "wifi"
    
    header.sourceComponent: EditDownArrowHeader{
        text: dsTr("Wi-Fi")
    }

    content.sourceComponent: Column { 
    }
}
