.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2010-2021, Deepin Technology Co., Ltd.
.\"
.TH "DDE-CONTROL-CENTER "1" "2021-03-26" "dde-control-center manpage"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
dde-control-center \- New control center for Deepin Desktop Environment.

.SH DESCRIPTION
.PP
.B dde-control-center
is a new control center for Deepin Desktop Environment.
.PP

.SH AUTHOR
.PP
.B dde-control-center
is maintain by Lv Peilong
.PP
This manual page was written by
.MT dongrui@\:uniontech.com
Uniontech
.ME
for the Debian Project (but may be used by others).