.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2021 wubowen <wubowen@uniontech.com>,
.\"
.TH "dde-control-center-wapper" "1" "2021-3-29" "Deepin"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
dde-control-center-wapper \- manual for deepin application.
.SH SYNOPSIS
dman [AppName]
.SH DESCRIPTION
DDE Control Center Wapper binary.
.PP
DDE Control Center Wapper is the control panel of Deepin Desktop Environment.
.SH OPTIONS
.PP
-h   show help info
.PP
-v   show version
.SH SEE ALSO
https://github.com/linuxdeepin/dde-control-center
.SH AUTHOR
.PP
.B dde-control-center-wapper
is written by Deepin Technology Co., Ltd.
.PP
This manual page was written by
.MT wubowen@\:uniontech.com
Wu Bo Wen
.ME
for the Debian Project (but may be used by others)
