#!/bin/sh

if ! getent passwd deepin_pwd_changer >/dev/null; then
    useradd -M -r deepin_pwd_changer
    usermod -L deepin_pwd_changer
fi

chown deepin_pwd_changer:deepin_pwd_changer /usr/lib/dde-control-center/reset-password-dialog
chmod 500 /usr/lib/dde-control-center/reset-password-dialog

exit 0
