// This file is automatically generated, please don't edit manually.
import QtQuick 2.1
import Deepin.Widgets 1.0
import "../edit"

BaseEditSection { 
    id: sectionMobile
    virtualSection: "vs-mobile"
    
    header.sourceComponent: EditDownArrowHeader{
        text: dsTr("Mobile")
    }

    content.sourceComponent: Column { 
        EditLineComboBox {
            id: lineVsMobileVkMobileServiceType
            connectionSession: sectionMobile.connectionSession
            availableSections: sectionMobile.availableSections
            availableKeys: sectionMobile.availableKeys
            errors: sectionMobile.errors
            section: "vs-mobile"
            key: "vk-mobile-service-type"
            text: dsTr("Service Type")
        }
        EditLineEditComboBox {
            id: lineGsmApn
            connectionSession: sectionMobile.connectionSession
            availableSections: sectionMobile.availableSections
            availableKeys: sectionMobile.availableKeys
            errors: sectionMobile.errors
            section: "gsm"
            key: "apn"
            text: dsTr("APN")
        }
        EditLineTextInput {
            id: lineGsmNumber
            connectionSession: sectionMobile.connectionSession
            availableSections: sectionMobile.availableSections
            availableKeys: sectionMobile.availableKeys
            errors: sectionMobile.errors
            section: "gsm"
            key: "number"
            text: dsTr("Number")
        }
        EditLineTextInput {
            id: lineGsmUsername
            connectionSession: sectionMobile.connectionSession
            availableSections: sectionMobile.availableSections
            availableKeys: sectionMobile.availableKeys
            errors: sectionMobile.errors
            section: "gsm"
            key: "username"
            text: dsTr("Username")
        }
        EditLinePasswordInput {
            id: lineGsmPassword
            connectionSession: sectionMobile.connectionSession
            availableSections: sectionMobile.availableSections
            availableKeys: sectionMobile.availableKeys
            errors: sectionMobile.errors
            section: "gsm"
            key: "password"
            text: dsTr("Password")
        }
        EditLineTextInput {
            id: lineGsmNetworkId
            connectionSession: sectionMobile.connectionSession
            availableSections: sectionMobile.availableSections
            availableKeys: sectionMobile.availableKeys
            errors: sectionMobile.errors
            section: "gsm"
            key: "network-id"
            text: dsTr("Network ID")
        }
        EditLineComboBox {
            id: lineGsmNetworkType
            connectionSession: sectionMobile.connectionSession
            availableSections: sectionMobile.availableSections
            availableKeys: sectionMobile.availableKeys
            errors: sectionMobile.errors
            section: "gsm"
            key: "network-type"
            text: dsTr("Type")
        }
        EditLineSwitchButton {
            id: lineGsmHomeOnly
            connectionSession: sectionMobile.connectionSession
            availableSections: sectionMobile.availableSections
            availableKeys: sectionMobile.availableKeys
            errors: sectionMobile.errors
            section: "gsm"
            key: "home-only"
            text: dsTr("Home Network Only")
        }
        EditLinePasswordInput {
            id: lineGsmPin
            connectionSession: sectionMobile.connectionSession
            availableSections: sectionMobile.availableSections
            availableKeys: sectionMobile.availableKeys
            errors: sectionMobile.errors
            section: "gsm"
            key: "pin"
            text: dsTr("PIN")
        }
        EditLineTextInput {
            id: lineCdmaNumber
            connectionSession: sectionMobile.connectionSession
            availableSections: sectionMobile.availableSections
            availableKeys: sectionMobile.availableKeys
            errors: sectionMobile.errors
            section: "cdma"
            key: "number"
            text: dsTr("Number")
        }
        EditLineTextInput {
            id: lineCdmaUsername
            connectionSession: sectionMobile.connectionSession
            availableSections: sectionMobile.availableSections
            availableKeys: sectionMobile.availableKeys
            errors: sectionMobile.errors
            section: "cdma"
            key: "username"
            text: dsTr("Username")
        }
        EditLinePasswordInput {
            id: lineCdmaPassword
            connectionSession: sectionMobile.connectionSession
            availableSections: sectionMobile.availableSections
            availableKeys: sectionMobile.availableKeys
            errors: sectionMobile.errors
            section: "cdma"
            key: "password"
            text: dsTr("Password")
        }
    }
}
