var currentSystemBindings = {
	0:   "Launcher",
	1:   "Terminal",
	2:   "Lock screen",
	3:   "Show/Hide the dock",
	4:   "Logout",
	5:   "Launch user manual",
	6:   "Take a screenshot",
	7:   "Take a screenshot of full screen",
	8:   "Take a screenshot of a window",
	9:   "Take a screenshot delayed",
	10:  "File manager",
	645: "Show desktop",
	670: "Switch applications",
	671: "Reverse switch applications",
	302: "Launch calculator",
	305: "Eject",
	306: "Launch email client",
	334: "Launch web browser",
	314: "Launch media player",
	319: "Play (or play/pause)",
	318: "Pause playback",
	326: "Stop playback",
	329: "Volume down",
	330: "Volume mute",
	331: "Volume up",
	320: "Previous track",
	315: "Next track",
	600: "Activate the window menu",
	601: "Move window",
	602: "Resize window",
	603: "Close window",
	611: "Maximize window",
	614: "Minimize window",
	676: "Toggle shaded state",
	677: "Restore window",
	654: "Switch to workspace 1",
	655: "Switch to workspace 2",
	656: "Switch to workspace 3",
	657: "Switch to workspace 4",
	666: "Switch to workspace down",
	667: "Switch to workspace left",
	668: "Switch to workspace right",
	669: "Switch to workspace up",
	900: "Move to workspace 1",
	901: "Move to workspace 2",
	902: "Move to workspace 3",
	903: "Move to workspace 4",
	636: "Move to workspace down",
	637: "Move to workspace left",
	638: "Move to workspace right",
	639: "Move to workspace up",
	800: "Switch applications with 3D effect",
	801: "Reverse switch applications with 3D effect"
}
