TimeSpinBox #SpinLabel {
    font-size:52px;
    color:white;
    background-color:#151617;
    border-radius:5px;
}

TimeSpinBox #SpinAddBtn {
    qproperty-normalPic:url(modules/datetime/icons/arrow_up_normal.png);
    qproperty-hoverPic:url(modules/datetime/icons/arrow_up_hover.png);
    qproperty-pressPic:url(modules/datetime/icons/arrow_up_press.png);
}

TimeSpinBox #SpinSubBtn {
    qproperty-normalPic:url(modules/datetime/icons/arrow_down_normal.png);
    qproperty-hoverPic:url(modules/datetime/icons/arrow_down_hover.png);
    qproperty-pressPic:url(modules/datetime/icons/arrow_down_press.png);
}

