/**
 * Copyright (C) 2015 Deepin Technology Co., Ltd.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 **/

/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c DBusDiskMount -p dbusdiskmount com.deepin.daemon.DiskMount.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "dbusdiskmount.h"

/*
 * Implementation of interface class DBusDiskMount
 */

DBusDiskMount::DBusDiskMount(QObject *parent)
    : QDBusAbstractInterface(staticServerPath(), staticInterfacePath(), staticInterfaceName(), QDBusConnection::sessionBus(), parent)
{
    qDBusRegisterMetaType<DiskInfo>();
    qDBusRegisterMetaType<DiskInfoList>();
    QDBusConnection::sessionBus().connect(this->service(), this->path(), "org.freedesktop.DBus.Properties",  "PropertiesChanged","sa{sv}as", this, SLOT(__propertyChanged__(QDBusMessage)));
}

DBusDiskMount::~DBusDiskMount()
{
    QDBusConnection::sessionBus().disconnect(service(), path(), "org.freedesktop.DBus.Properties",  "PropertiesChanged",  "sa{sv}as", this, SLOT(propertyChanged(QDBusMessage)));
}

QDBusArgument &operator<<(QDBusArgument &argument, const DiskInfo &diskInfo)
{
    argument.beginStructure();
    argument << diskInfo.name
        << diskInfo.type
        << diskInfo.canUnmount
        << diskInfo.canEject
        << diskInfo.used
        << diskInfo.size
        << diskInfo.path
        << diskInfo.uUID
        << diskInfo.mountPoint
        << diskInfo.icon;
    argument.endStructure();
    return argument;
}

const QDBusArgument &operator>>(const QDBusArgument &argument, DiskInfo &diskInfo)
{
    argument.beginStructure();
    argument >> diskInfo.name
            >> diskInfo.type
            >> diskInfo.canUnmount
            >> diskInfo.canEject
            >> diskInfo.used
            >> diskInfo.size
            >> diskInfo.path
            >> diskInfo.uUID
            >> diskInfo.mountPoint
            >> diskInfo.icon;
    argument.endStructure();
    return argument;
}

