// This file is automatically generated, please don't edit manully.
import QtQuick 2.1
import Deepin.Widgets 1.0
import "../components"

BaseEditSection {
    id: sectionMobileCdma
    section: "mobile-cdma"
    
    header.sourceComponent: EditDownArrowHeader{
        text: dsTr("Mobile")
    }

    content.sourceComponent: Column { 
        EditLineTextInput {
            id: lineNumber
            key: "number"
            text: dsTr("Number")
        }
        EditLineTextInput {
            id: lineUsername
            key: "username"
            text: dsTr("Username")
        }
        EditLinePasswordInput {
            id: linePassword
            key: "password"
            text: dsTr("Password")
        }
    }
}
