// This file is automatically generated, please don't edit manully.
import QtQuick 2.1
import Deepin.Widgets 1.0
import "../components"

BaseEditSection {
    id: sectionEthernet
    section: "ethernet"
    
    header.sourceComponent: EditDownArrowHeader{
        text: dsTr("Ethernet")
    }

    content.sourceComponent: Column { 
        EditLineEditComboBox {
            id: lineMacAddress
            key: "mac-address"
            text: dsTr("Device MAC Addr")
        }
        EditLineTextInput {
            id: lineClonedMacAddress
            key: "cloned-mac-address"
            text: dsTr("Cloned MAC Addr")
        }
        EditLineSwitchButton {
            id: lineVkEnableMtu
            key: "vk-enable-mtu"
            text: dsTr("Custom MTU")
        }
        EditLineSpinner {
            id: lineMtu
            key: "mtu"
            text: dsTr("MTU")
            max: 10000
            min: 0
        }
    }
}
