// This file is automatically generated, please don't edit manully.
import QtQuick 2.1
import Deepin.Widgets 1.0
import "../components"

BaseEditSection {
    id: sectionIpv6
    section: "ipv6"
    
    header.sourceComponent: EditDownArrowHeader{
        text: dsTr("IPv6")
    }

    content.sourceComponent: Column { 
        EditLineComboBox {
            id: lineMethod
            key: "method"
            text: dsTr("Method")
        }
        EditLineTextInput {
            id: lineVkAddressesAddress
            key: "vk-addresses-address"
            text: dsTr("IP Address")
        }
        EditLineSpinner {
            id: lineVkAddressesPrefix
            key: "vk-addresses-prefix"
            text: dsTr("Prefix")
            max: 128
            min: 0
        }
        EditLineTextInput {
            id: lineVkAddressesGateway
            key: "vk-addresses-gateway"
            text: dsTr("Gateway")
        }
        EditLineTextInput {
            id: lineVkDns
            key: "vk-dns"
            text: dsTr("DNS Server")
        }
    }
}
