/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-control-center/dcc-old/src/plugin-display/wayland/libwayqt/protocols/treeland-output-management.xml -a ./dde-control-center/toolGenerate/qdbusxml2cpp/treeland-output-managementAdaptor -i ./dde-control-center/toolGenerate/qdbusxml2cpp/treeland-output-management.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-control-center/toolGenerate/qdbusxml2cpp/treeland-output-managementAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

