/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-control-center/dcc-old/src/plugin-display/wayland/libwayqt/protocols/wlr-output-management-unstable-v1.xml -a ./dde-control-center/toolGenerate/qdbusxml2cpp/wlr-output-management-unstable-v1Adaptor -i ./dde-control-center/toolGenerate/qdbusxml2cpp/wlr-output-management-unstable-v1.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef WLR-OUTPUT-MANAGEMENT-UNSTABLE-V1ADAPTOR_H
#define WLR-OUTPUT-MANAGEMENT-UNSTABLE-V1ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-control-center/toolGenerate/qdbusxml2cpp/wlr-output-management-unstable-v1.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

#endif
