name: CI Build

on:
  push:
    branches:
      - uos

  pull_request:
    branches:
      - uos

jobs:
  archlinux:
    name: Archlinux Build Check
    runs-on: ubuntu-latest
    container: docker.io/library/archlinux:latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Refresh pacman repository
        run: pacman -Syy
      - name: Install build dependencies
        run: pacman -S --noconfirm base-devel cmake ninja qt5-tools deepin-qt-dbus-factory dtkwidget networkmanager-qt deepin-network-utils udisks2-qt5 libpwquality
      - name: CMake & Make
        run: |
          mkdir build
          cd build
          cmake ../ -G Ninja
          ninja
