name: CI Build

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  archlinux:
    name: Archlinux Build Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: build
        uses: justforlxz/deepin-git-action@v1
        with:
          repo: deepin-control-center
