/**
 * Copyright (C) 2015 Deepin Technology Co., Ltd.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 **/

/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a DBusMouse mouse.xml -p dbusmouse
 *
 * qdbusxml2cpp is Copyright (C) 2015 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "dbusmouse.h"

/*
 * Implementation of interface class ComDeepinDaemonInputDeviceMouseInterface
 */

ComDeepinDaemonInputDeviceMouseInterface::ComDeepinDaemonInputDeviceMouseInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
    QDBusConnection::sessionBus().connect(this->service(), this->path(), "org.freedesktop.DBus.Properties",  "PropertiesChanged","sa{sv}as", this, SLOT(__propertyChanged__(QDBusMessage)));
}

ComDeepinDaemonInputDeviceMouseInterface::~ComDeepinDaemonInputDeviceMouseInterface()
{
    QDBusConnection::sessionBus().disconnect(service(), path(), "org.freedesktop.DBus.Properties",  "PropertiesChanged","sa{sv}as", this, SLOT(__propertyChanged__(QDBusMessage)));
}

MouseDeviceList::MouseDeviceList()
{

}

MouseDeviceList::~MouseDeviceList()
{

}

QDBusArgument& operator<< (QDBusArgument & argument, const MouseDeviceList & deviceList)
{
    argument.beginStructure();
    argument << deviceList.m_name;
    argument << deviceList.m_deviceId;
    argument << deviceList.m_active;
    argument.endStructure();
    return argument;
}

const QDBusArgument& operator>> (const QDBusArgument & argument, MouseDeviceList & deviceList)
{
    argument.beginStructure();
    argument >> deviceList.m_name >> deviceList.m_deviceId >> deviceList.m_active;
    argument.endStructure();
    return argument;

}

void MouseDeviceList::printValue()
{
    qDebug() << "device list";
    qDebug() << m_name << m_deviceId << m_active;
}

void MouseDeviceList::registerMetaType()
{
    qRegisterMetaType<MouseDeviceList>("Message");
    qDBusRegisterMetaType<MouseDeviceList>();
}
