/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a DBusTouchpad touchpad.xml -p dbustouchpad
 *
 * qdbusxml2cpp is Copyright (C) 2015 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "dbustouchpad.h"

/*
 * Implementation of interface class ComDeepinDaemonInputDeviceTouchPadInterface
 */

ComDeepinDaemonInputDeviceTouchPadInterface::ComDeepinDaemonInputDeviceTouchPadInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

ComDeepinDaemonInputDeviceTouchPadInterface::~ComDeepinDaemonInputDeviceTouchPadInterface()
{
}



TouchpadDeviceList::TouchpadDeviceList()
{

}

TouchpadDeviceList::~TouchpadDeviceList()
{

}

QDBusArgument& operator<< (QDBusArgument & argument, const TouchpadDeviceList & deviceList)
{
    argument.beginStructure();
    argument << deviceList.m_name;
    argument << deviceList.m_deviceId;
    argument << deviceList.m_active;
    argument.endStructure();
    return argument;
}

const QDBusArgument& operator>> (const QDBusArgument & argument, TouchpadDeviceList & deviceList)
{
    argument.beginStructure();
    argument >> deviceList.m_name >> deviceList.m_deviceId >> deviceList.m_active;
    argument.endStructure();
    return argument;
}

void TouchpadDeviceList::registerMetaType()
{
    qRegisterMetaType<TouchpadDeviceList>("Message");
    qDBusRegisterMetaType<TouchpadDeviceList>();
}

